const SET_SEARCH_CITY = "SET_SEARCH_CITY";
const ADD_CITY_WEATHER = "ADD_CITY_WEATHER";
const END_OF_LOADING = "END_OF_LOADING";
const ERROR_OCCURED = "ERROR_OCCURED";

export { ADD_CITY_WEATHER, END_OF_LOADING, ERROR_OCCURED, SET_SEARCH_CITY };
